all: build

build:
	gcc -O0 -D IJK permutation.c -o premuIJK.out
	gcc -O0 -D IKJ permutation.c -o premuIKJ.out
	gcc -O0 -D JIK permutation.c -o premuJIK.out
	gcc -O0 -D JKI permutation.c -o premuJKI.out
	gcc -O0 -D KIJ permutation.c -o premuKIJ.out
	gcc -O0 -D KJI permutation.c -o premuKJI.out
	